server:
  port: 8080

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/sakila
      username: root
      password: 123456

environments:
  dev:
    url: http://dev.bar.com
    name: Developer Setup
  prod:
    url: http://foo.bar.com
    name: My Cool App


my-example:
  url:
    - http://example.com
    - http://spring.io
  auth:
    username: aaa
    password: bbb
